<?php defined('ABSPATH') or die(); 

function ad_acfbuilder_add_fields() {

	acf_add_local_field_group(array (
		'key' => 'group_58c6bfd3a0239',
		'title' => __('AD ACF Builder', 'ad-acfb'),
		'fields' => array (
			array (
				'key' => 'field_58c6bfd90e6b4',
				'label' => __('Page Builder', 'ad-acfb'),
				'name' => 'page_builder',
				'type' => 'flexible_content',
				'instructions' => __('Add some content!', 'ad-acfb'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array (
					'58c6bfee6ec2e' => array (
						'key' => '58c6bfee6ec2e',
						'name' => 'text_block',
						'label' => 'Text block',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_58c6c01f0e6b5',
								'label' => 'Layout',
								'name' => 'text_block_layout',
								'type' => 'select',
								'instructions' => 'Choisir un bloc sur une, deux ou 3 colonnes.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'1col' => 'Une colonne',
									'2col' => 'Deux colonnes',
									'3col' => 'Trois colonnes',
								),
								'default_value' => array (
									0 => '1col',
								),
								'allow_null' => 1,
								'multiple' => 0,
								'ui' => 0,
								'ajax' => 0,
								'return_format' => 'value',
								'placeholder' => '',
							),
							array (
								'key' => 'field_58c6c0850e6b6',
								'label' => 'Text area',
								'name' => 'text_block_area1',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
							array (
								'key' => 'field_58c6c0a70e6b7',
								'label' => 'Text area - 2',
								'name' => 'text_block_area2',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_58c6c01f0e6b5',
											'operator' => '==',
											'value' => '2col',
										),
									),
									array (
										array (
											'field' => 'field_58c6c01f0e6b5',
											'operator' => '==',
											'value' => '3col',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
							array (
								'key' => 'field_58c6c0c10e6b9',
								'label' => 'Text area - 3',
								'name' => 'text_block_area3',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array (
									array (
										array (
											'field' => 'field_58c6c01f0e6b5',
											'operator' => '==',
											'value' => '3col',
										),
									),
								),
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'58c6c0ee0e6bb' => array (
						'key' => '58c6c0ee0e6bb',
						'name' => 'cta_block',
						'label' => 'Call To Action block',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_58c6c10ae5a58',
								'label' => 'Text area',
								'name' => 'cta_block_text',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
							array (
								'key' => 'field_58c6c1a0e5a5b',
								'label' => 'Lien interne',
								'name' => 'cta_block_link',
								'type' => 'page_link',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'post_type' => array (
								),
								'taxonomy' => array (
								),
								'allow_null' => 1,
								'allow_archives' => 1,
								'multiple' => 0,
							),
							array (
								'key' => 'field_58c6c1c3e5a5c',
								'label' => 'Lien externe',
								'name' => 'cta_block_url',
								'type' => 'url',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
							),
							array (
								'key' => 'field_58cbf56d6f745',
								'label' => 'Intitulé du lien',
								'name' => 'cta_block_link_title',
								'type' => 'text',
								'instructions' => 'Saisir l\'intitulé du bouton (facultatif)',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58c6c12fe5a59',
								'label' => 'Image d\'arrière-plan',
								'name' => 'cta_block_bg',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array (
								'key' => 'field_58c6c14ee5a5a',
								'label' => 'Couleur du texte',
								'name' => 'cta_block_color',
								'type' => 'checkbox',
								'instructions' => 'À cocher si vous utilisez une image d\'arrière-plan.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'white_text' => 'Texte en blanc',
								),
								'allow_custom' => 0,
								'save_custom' => 0,
								'default_value' => array (
								),
								'layout' => 'vertical',
								'toggle' => 0,
								'return_format' => 'value',
							),
						),
						'min' => '',
						'max' => '',
					),
					'58c6c1e5e5a5d' => array (
						'key' => '58c6c1e5e5a5d',
						'name' => 'content_gallery_block',
						'label' => 'Bloc galerie (contenus)',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_58c6c217e5a5e',
								'label' => 'Titre',
								'name' => 'content_gallery_block_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58cbdaac94eed',
								'label' => 'Nombre de colonnes',
								'name' => 'content_gallery_block_cols',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'col-6' => '2 colonnes',
									'col-4' => '3 colonnes',
									'col-3' => '4 colonnes',
									'col-2' => '6 colonnes',
								),
								'default_value' => array (
									0 => 'col-4',
								),
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'ajax' => 0,
								'return_format' => 'value',
								'placeholder' => '',
							),
							array (
								'key' => 'field_58c6c224e5a5f',
								'label' => 'Sélection de contenus',
								'name' => 'content_gallery_block_content',
								'type' => 'post_object',
								'instructions' => 'Choisir les pages ou articles à faire figurer dans la galerie',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'post_type' => array (
									0 => 'page',
									1 => 'post',
									2 => 'offer',
								),
								'taxonomy' => array (
								),
								'allow_null' => 0,
								'multiple' => 1,
								'return_format' => 'object',
								'ui' => 1,
							),
						),
						'min' => '',
						'max' => '',
					),
					'58c6c277e5a60' => array (
						'key' => '58c6c277e5a60',
						'name' => 'gallery_block',
						'label' => 'Bloc galerie (images)',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_58c6c277e5a61',
								'label' => 'Titre',
								'name' => 'gallery_block_title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58cbd8f6d88e6',
								'label' => 'Nombre de colonnes',
								'name' => 'gallery_block_cols',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'col-6' => '2 colonnes',
									'col-4' => '3 colonnes',
									'col-3' => '4 colonnes',
									'col-2' => '6 colonnes',
								),
								'default_value' => array (
									0 => 'col-3',
								),
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'ajax' => 0,
								'return_format' => 'value',
								'placeholder' => '',
							),
							array (
								'key' => 'field_58c6c290e5a63',
								'label' => 'Galerie',
								'name' => 'gallery_block_img',
								'type' => 'gallery',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'min' => '',
								'max' => '',
								'insert' => 'append',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'58c6cea836dde' => array (
						'key' => '58c6cea836dde',
						'name' => 'gmap_block',
						'label' => 'Bloc Google Map',
						'display' => 'block',
						'sub_fields' => array (
							array (
								'key' => 'field_58c6ceb936ddf',
								'label' => 'Carte',
								'name' => 'gmap_block_map',
								'type' => 'google_map',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'center_lat' => '48.8554291',
								'center_lng' => '2.3516978',
								'zoom' => '',
								'height' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add a block',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

}

add_action('acf/init', 'ad_acfbuilder_add_fields');