<?php defined('ABSPATH') or die(); 

function ad_acfbuilder_add_fields() {

acf_add_local_field_group(array (
	'key' => 'group_58c6bfd3a0239',
	'title' => 'AD ACF Builder',
	'fields' => array (
		array (
			'key' => 'field_58c6bfd90e6b4',
			'label' => 'Page Builder',
			'name' => 'page_builder',
			'type' => 'flexible_content',
			'instructions' => 'Add some content!',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array (
				'58c6bfee6ec2e' => array (
					'key' => '58c6bfee6ec2e',
					'name' => 'text_block',
					'label' => 'Content block',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_58c6c01f0e6b5',
							'label' => 'Layout',
							'name' => 'text_block_layout',
							'type' => 'select',
							'instructions' => 'Choose the layout for this block: 1, 2 or 3 columns',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'1col' => '1 column',
								'2col' => '2 columns',
								'3col' => '3 columns',
							),
							'default_value' => array (
								0 => '1col',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_5968734836216',
							'label' => 'Content',
							'name' => 'text_block_group',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array (
								array (
									'ID' => 128,
									'key' => 'field_58c6c0850e6b6',
									'label' => 'Content Area',
									'name' => 'text_block_area1',
									'prefix' => 'acf',
									'type' => 'wysiwyg',
									'value' => NULL,
									'menu_order' => 0,
									'instructions' => '',
									'required' => 0,
									'id' => '',
									'class' => '',
									'conditional_logic' => 0,
									'parent' => 169,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'_name' => 'text_block_area1',
									'_prepare' => 0,
									'_valid' => 1,
									'parent_layout' => '58c6bfee6ec2e',
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
								array (
									'ID' => 129,
									'key' => 'field_58c6c0a70e6b7',
									'label' => 'Content Area',
									'name' => 'text_block_area2',
									'prefix' => 'acf',
									'type' => 'wysiwyg',
									'value' => NULL,
									'menu_order' => 1,
									'instructions' => '',
									'required' => 0,
									'id' => '',
									'class' => '',
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_58c6c01f0e6b5',
												'operator' => '==',
												'value' => '2col',
											),
										),
										array (
											array (
												'field' => 'field_58c6c01f0e6b5',
												'operator' => '==',
												'value' => '3col',
											),
										),
									),
									'parent' => 169,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'_name' => 'text_block_area2',
									'_prepare' => 0,
									'_valid' => 1,
									'parent_layout' => '58c6bfee6ec2e',
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
								array (
									'ID' => 130,
									'key' => 'field_58c6c0c10e6b9',
									'label' => 'Content Area',
									'name' => 'text_block_area3',
									'prefix' => 'acf',
									'type' => 'wysiwyg',
									'value' => NULL,
									'menu_order' => 2,
									'instructions' => '',
									'required' => 0,
									'id' => '',
									'class' => '',
									'conditional_logic' => array (
										array (
											array (
												'field' => 'field_58c6c01f0e6b5',
												'operator' => '==',
												'value' => '3col',
											),
										),
									),
									'parent' => 169,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'_name' => 'text_block_area3',
									'_prepare' => 0,
									'_valid' => 1,
									'parent_layout' => '58c6bfee6ec2e',
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'58c6c0ee0e6bb' => array (
					'key' => '58c6c0ee0e6bb',
					'name' => 'cta_block',
					'label' => 'Call To Action block',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_58c6c10ae5a58',
							'label' => 'Text Area',
							'name' => 'cta_block_text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array (
							'key' => 'field_59686fbd2e6f8',
							'label' => 'Link',
							'name' => 'cta_block_link',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array (
							'key' => 'field_59686ee62e6f7',
							'label' => 'Style',
							'name' => 'cta_block_style',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array (
								array (
									'ID' => 177,
									'key' => 'field_5968ab7c045cd',
									'label' => 'Button Text Color',
									'name' => 'cta_block_btncolor',
									'prefix' => 'acf',
									'type' => 'color_picker',
									'value' => NULL,
									'menu_order' => 0,
									'instructions' => '',
									'required' => 0,
									'id' => '',
									'class' => '',
									'conditional_logic' => 0,
									'parent' => 166,
									'wrapper' => array (
										'width' => '50%',
										'class' => '',
										'id' => '',
									),
									'_name' => 'cta_block_btncolor',
									'_prepare' => 0,
									'_valid' => 1,
									'parent_layout' => '58c6c0ee0e6bb',
									'default_value' => '#ffffff',
								),
								array (
									'ID' => 178,
									'key' => 'field_5968aba7045ce',
									'label' => 'Button Background Color',
									'name' => 'cta_block_btnbg',
									'prefix' => 'acf',
									'type' => 'color_picker',
									'value' => NULL,
									'menu_order' => 1,
									'instructions' => '',
									'required' => 0,
									'id' => '',
									'class' => '',
									'conditional_logic' => 0,
									'parent' => 166,
									'wrapper' => array (
										'width' => '50',
										'class' => '',
										'id' => '',
									),
									'_name' => 'cta_block_btnbg',
									'_prepare' => 0,
									'_valid' => 1,
									'parent_layout' => '58c6c0ee0e6bb',
									'default_value' => '#FF0055',
								),
								array (
									'ID' => 136,
									'key' => 'field_58c6c14ee5a5a',
									'label' => 'Text Color',
									'name' => 'cta_block_color',
									'prefix' => 'acf',
									'type' => 'checkbox',
									'value' => NULL,
									'menu_order' => 2,
									'instructions' => 'Check if you have set a dark background.',
									'required' => 0,
									'id' => '',
									'class' => '',
									'conditional_logic' => 0,
									'parent' => 166,
									'wrapper' => array (
										'width' => '33',
										'class' => '',
										'id' => '',
									),
									'_name' => 'cta_block_color',
									'_prepare' => 0,
									'_valid' => 1,
									'parent_layout' => '58c6c0ee0e6bb',
									'choices' => array (
										'white_text' => 'White Text',
									),
									'allow_custom' => 0,
									'save_custom' => 0,
									'default_value' => array (
									),
									'layout' => 'vertical',
									'toggle' => 0,
									'return_format' => 'value',
								),
								array (
									'ID' => 145,
									'key' => 'field_5967cd63bc399',
									'label' => 'Background Color',
									'name' => 'cta_block_bgcolor',
									'prefix' => 'acf',
									'type' => 'color_picker',
									'value' => NULL,
									'menu_order' => 3,
									'instructions' => '',
									'required' => 0,
									'id' => '',
									'class' => '',
									'conditional_logic' => 0,
									'parent' => 166,
									'wrapper' => array (
										'width' => '33',
										'class' => '',
										'id' => '',
									),
									'_name' => 'cta_block_bgcolor',
									'_prepare' => 0,
									'_valid' => 1,
									'parent_layout' => '58c6c0ee0e6bb',
									'default_value' => '#FFFFFF',
								),
								array (
									'ID' => 135,
									'key' => 'field_58c6c12fe5a59',
									'label' => 'Background Image',
									'name' => 'cta_block_bg',
									'prefix' => 'acf',
									'type' => 'image',
									'value' => NULL,
									'menu_order' => 4,
									'instructions' => '',
									'required' => 0,
									'id' => '',
									'class' => '',
									'conditional_logic' => 0,
									'parent' => 166,
									'wrapper' => array (
										'width' => '33',
										'class' => '',
										'id' => '',
									),
									'_name' => 'cta_block_bg',
									'_prepare' => 0,
									'_valid' => 1,
									'parent_layout' => '58c6c0ee0e6bb',
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array (
									'ID' => 204,
									'key' => 'field_596f6dc312601',
									'label' => 'Overlay',
									'name' => 'cta_block_overlay',
									'prefix' => 'acf',
									'type' => 'checkbox',
									'value' => NULL,
									'menu_order' => 5,
									'instructions' => 'Add an image overlay',
									'required' => 0,
									'id' => '',
									'class' => '',
									'conditional_logic' => 0,
									'parent' => 166,
									'wrapper' => array (
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'_name' => 'cta_block_overlay',
									'_prepare' => 0,
									'_valid' => 1,
									'parent_layout' => '58c6c0ee0e6bb',
									'choices' => array (
										'balck_overlay' => 'Black Overlay',
									),
									'allow_custom' => 0,
									'save_custom' => 0,
									'default_value' => array (
									),
									'layout' => 'vertical',
									'toggle' => 0,
									'return_format' => 'value',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				'58c6c277e5a60' => array (
					'key' => '58c6c277e5a60',
					'name' => 'gallery_block',
					'label' => 'Photo Gallery',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_58c6c277e5a61',
							'label' => 'Title (h2)',
							'name' => 'gallery_block_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58cbd8f6d88e6',
							'label' => 'Columns',
							'name' => 'gallery_block_cols',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'col-6' => '2 colums',
								'col-4' => '3 colums',
								'col-3' => '4 colums',
								'col-2' => '6 colums',
							),
							'default_value' => array (
								0 => 'col-3',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_58c6c290e5a63',
							'label' => 'Gallery',
							'name' => 'gallery_block_img',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'insert' => 'append',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'58c6c1e5e5a5d' => array (
					'key' => '58c6c1e5e5a5d',
					'name' => 'content_gallery_block',
					'label' => 'Content Gallery',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_58c6c217e5a5e',
							'label' => 'Title (h2)',
							'name' => 'content_gallery_block_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_58cbdaac94eed',
							'label' => 'Columns',
							'name' => 'content_gallery_block_cols',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'col-6' => '2 columns',
								'col-4' => '3 columns',
								'col-3' => '4 columns',
								'col-2' => '6 columns',
							),
							'default_value' => array (
								0 => 'col-4',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_58c6c224e5a5f',
							'label' => 'Content',
							'name' => 'content_gallery_block_content',
							'type' => 'relationship',
							'instructions' => 'Choose the posts, pages or custom post type you want in the gallery',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
							),
							'taxonomy' => array (
							),
							'filters' => array (
								0 => 'search',
								1 => 'post_type',
								2 => 'taxonomy',
							),
							'elements' => array (
								0 => 'featured_image',
							),
							'min' => '',
							'max' => '',
							'return_format' => 'object',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Content',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

}

add_action('acf/init', 'ad_acfbuilder_add_fields');